version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - k-anonymity
      - l-diversity
      - t-closeness
      - gaussian-copula
      - ctgan-synthesis
      - tvae-synthesis
      - dp-laplace
      - dp-exponential
      - dp-gaussian
      - dp-queries-lp
      - dp-queries-ep
      - frontend
    networks:
      - data-anonymization-tool-network

  k-anonymity:
    image: ghcr.io/data-anonymization-tool/k-anonymity:latest
    pull_policy: always
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=k-anonymity.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5001
    volumes:
      - ./k-anonymity:/app
    networks:
      - data-anonymization-tool-network

  l-diversity:
    image: ghcr.io/data-anonymization-tool/l-diversity:latest
    pull_policy: always
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=l-diversity.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5002
    volumes:
      - ./l-diversity:/app
    networks:
      - data-anonymization-tool-network

  t-closeness:
    image: ghcr.io/data-anonymization-tool/t-closeness:latest
    pull_policy: always
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=t-closeness.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5003
    volumes:
      - ./t-closeness:/app
    networks:
      - data-anonymization-tool-network
  gaussian-copula:
    image: ghcr.io/data-anonymization-tool/gaussian-copula:latest
    pull_policy: always
    ports:
      - "5004:5004"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=gaussian-copula.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5004
    volumes:
      - ./gaussian-copula:/app
    networks:
      - data-anonymization-tool-network

  ctgan-synthesis:
    image: ghcr.io/data-anonymization-tool/ctgan-synthesis:latest
    pull_policy: always
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=ctgan-synthesis.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5005
    volumes:
      - ./ctgan-synthesis:/app
    networks:
      - data-anonymization-tool-network

  tvae-synthesis:
    image: ghcr.io/data-anonymization-tool/tvae-synthesis:latest
    pull_policy: always
    ports:
      - "5006:5006"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=tvae-synthesis.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5006
    volumes:
      - ./tvae-synthesis:/app
    networks:
      - data-anonymization-tool-network

  dp-laplace:
    image: ghcr.io/data-anonymization-tool/dp-laplace:latest
    pull_policy: always
    ports:
      - "5007:5007"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=dp-laplace.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5007
    volumes:
      - ./dp-laplace:/app
    networks:
      - data-anonymization-tool-network

  dp-exponential:
    image: ghcr.io/data-anonymization-tool/dp-exponential:latest
    pull_policy: always
    ports:
      - "5008:5008"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=dp-exponential.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5008
    volumes:
      - ./dp-exponential:/app
    networks:
      - data-anonymization-tool-network

  dp-gaussian:
    image: ghcr.io/data-anonymization-tool/dp-gaussian:latest
    pull_policy: always
    ports:
      - "5009:5009"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=dp-gaussian.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5009
    volumes:
      - ./dp-gaussian:/app
    networks:
      - data-anonymization-tool-network

  dp-queries-lp:
    image: ghcr.io/data-anonymization-tool/dp-queries-lp:latest
    pull_policy: always
    ports:
      - "5010:5010"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=dp-queries-lp.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5010
    volumes:
      - ./dp-queries-lp:/app
    networks:
      - data-anonymization-tool-network

  dp-queries-ep:
    image: ghcr.io/data-anonymization-tool/dp-queries-ep:latest
    pull_policy: always
    ports:
      - "5011:5011"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=dp-queries-ep.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5011
    volumes:
      - ./dp-queries-ep:/app
    networks:
      - data-anonymization-tool-network

  frontend:
    pull_policy: always
    image: ghcr.io/data-anonymization-tool/data-anonymization-ui:latest
    ports:
      - "3000:80"
    restart: always
    environment:
      - REACT_APP_GITHUB_TOKEN=${REACT_APP_GITHUB_TOKEN}
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16 # Changed subnet here
          gateway: 172.30.0.1

  data-anonymization-tool-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.32.0.0/16 # Changed subnet here to avoid conflicts
          gateway: 172.32.0.1
