name: Publish Docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: 
          - k-anonymity
          - t-closeness
          - l-diversity
          - gaussian-copula
          - ctgan-synthesis
          - tvae-synthesis
          - dp-laplace
          - dp-exponential
          - dp-gaussian
          - dp-queries-lp
          - dp-queries-ep

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN_2 }}

      - name: Build and push Docker image for ${{ matrix.module }}
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.module }}
          file: ./${{ matrix.module }}/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.module }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.module }}:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.module }}:cache,mode=max
