name: Publish Docker images

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image for k-anonymity
        uses: docker/build-push-action@v2
        with:
          context: ./k-anonymity
          file: ./k-anonymity/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/k-anonymity:latest

      # Add more steps for other modules similarly
